apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app      # matches your deployment pods
  ports:
    - protocol: TCP
      port: 80           # port on the service (what users will use)
      targetPort: 3000   # port on the container
      nodePort: 30007    # port on the Minikube node
  type: NodePort         # exposes the service outside the cluster
